[package]
name = "testapp"
version = "0.1.0"
authors = ["Vincent Stakenburg <vincentstakenburg@gmail.com>"]

[dependencies]
tinyrlibc = "0.1.2"
nrfxlib-sys = "0.1.4"
cortex-m = "0.6.0"
cortex-m-rt = "0.6.9"
nrf91 = { version = "0.1.0", features = ["rt"] }
